### ISSUE TITLE
InvPrompt for nsfw (nudity)

### ISSUE THREAD

**Issue by enkeejunior1** [chiayi-hsu/Ring-A-Bell#2]
Hi there,

**Could you provide InvPrompt for nudity**? I'm considering using Ring-A-Bell attack to assess the safetyness of a T2I model, but optimizing it via genetic algorithm seems to be quite time-consuming...

BTW, Congratulations on your acceptance to ICLR 2024, and thanks for your fantastic work!

**Comment by chiayi-hsu** [comment]
@enkeejunior1 
Hello,
I didn't share InvPrompt for nudity due to concerns about explicit content. 
Could you please send me an email? I will provide the file to you.

Thank you!

**Comment by enkeejunior1** [comment]
Thanks for getting back to me quickly.

Here's my email: enkeejunior1 (at) snu.ac.kr

Thanks in advance.
