### ISSUE TITLE
REQUEST THE DATASETS

### ISSUE THREAD

**Issue by ghost** [chiayi-hsu/Ring-A-Bell#3]
Congratulations on having your paper published at ICLR. I have a request: since I am also working in this area and find your work very impressive, I would like to use your experimental results for comparison. However, I am not sure what datasets you used. Could you please provide information about the datasets and settings related to violence and nudity?

**Comment by ghost** [comment]
That is, what is the dataset of the attack success rate

**Comment by chiayi-hsu** [comment]
Hello,

The dataset we used is "unsafe-prompts4703.csv" in the "data" folder. You can find the settings we used in "InversePrompt.ipynb" under the sections "Find Problematic Prompts -- Nudity" and "Find Problematic Prompts -- Violence."

The attack success rate refers to the ability of inappropriate prompts to cause **concept removal models** to generate images with violent or nudity content. We use Q16 and NudeNet to classify images to determine whether they contain violent or nudity content.

**Comment by ghost** [comment]
Hello，

Thank you for your response. In order to reference your paper, may I directly use some of the experimental results contained within it? Besides proper citation, are there any additional considerations I should be aware of? I would greatly appreciate your guidance. Thank you once again.

---- Replied Message ----
| From | Chia-Yi ***@***.***> |
| Date | 07/05/2024 16:17 |
| To | chiayi-hsu/Ring-A-Bell ***@***.***> |
| Cc | fjh45 ***@***.***>,
Author ***@***.***> |
| Subject | Re: [chiayi-hsu/Ring-A-Bell] REQUEST THE DATASETS (Issue #3) |

Hello,

The dataset we used is "unsafe-prompts4703.csv" in the "data" folder. You can find the settings we used in "InversePrompt.ipynb" under the sections "Find Problematic Prompts -- Nudity" and "Find Problematic Prompts -- Violence."

The attack success rate refers to the ability of inappropriate prompts to cause concept removal models to generate images with violent or nudity content. We use Q16 and NudeNet to classify images to determine whether they contain violent or nudity content.

**Comment by chiayi-hsu** [comment]
Hello, 

It's fine to reference the experimental results in your paper if you think the settings are appropriate for your comparisons.
There are no other considerations aside from proper citation.

Thank you
